name: pesona_moa
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fluentui_icons: ^1.0.0
  firebase_core: ^2.4.1
  firebase_auth: ^4.2.5
  firebase_analytics: ^10.1.0
  cloud_firestore: ^4.3.1
  flutter_launcher_icons: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  generate : true
  uses-material-design: true
  assets:
    - assets/images/